version: '3.1'

services:
    cf_flowise:
        build:
          context: ./
          dockerfile: Dockerfile
        image: fseries
        container_name: fseries-1
        restart: always
        env_file:
             - .env
        ports:
          - 3000:3000